import type { StaffDashLabels } from "@/components/dashboards/StaffDashboardView";
import type { AdminDashLabels } from "@/components/dashboards/AdminDashboardView";

type TFn = (key: string) => string;

export function staffDashLabelsFromT(t: TFn, peopleLabel: string): StaffDashLabels {
  return {
    welcome: t("welcome"),
    salesToday: t("salesToday"),
    appointmentsToday: t("appointmentsToday"),
    unpaidInvoices: t("unpaidInvoices"),
    lowStock: t("lowStock"),
    peopleLabel,
    aiTitle: t("aiTitle"),
    dailyClose: t("dailyClose"),
    dailyCloseHint: t("dailyCloseHint"),
    closeIncome: t("closeIncome"),
    closeUnpaid: t("closeUnpaid"),
    closeNoShow: t("closeNoShow"),
    closeTxnToday: t("closeTxnToday"),
    closeLowStock: t("closeLowStock"),
    closeLhdnPending: t("closeLhdnPending"),
    closeLhdnRejected: t("closeLhdnRejected"),
    closeNone: t("closeNone"),
    closeOpenInvoices: t("closeOpenInvoices"),
    closeOpenInventory: t("closeOpenInventory"),
    closeOpenLhdn: t("closeOpenLhdn"),
    closeOpenPos: t("closeOpenPos"),
    quickActions: t("quickActions"),
    recentInvoices: t("recentInvoices"),
    upcomingAppointments: t("upcomingAppointments"),
    todaySales: t("todaySales"),
    todaySalesEmpty: t("todaySalesEmpty"),
    topSellers: t("topSellers"),
    topSellersEmpty: t("topSellersEmpty"),
    miniTimetable: t("miniTimetable"),
    occupied: t("occupied"),
    free: t("free"),
    clinicClosed: t("clinicClosed"),
    publicHoliday: t("publicHoliday"),
    myTasks: t("myTasks"),
    myScore: t("myScore"),
    noTasks: t("noTasks"),
    markDone: t("markDone"),
    invoices: t("invoicesLink"),
    appointments: t("appointmentsLink"),
    pos: t("posLink"),
    inventory: t("inventoryLink"),
  };
}

export function adminDashLabelsFromT(t: TFn, peopleLabel: string): AdminDashLabels {
  return {
    welcome: t("welcome"),
    subtitle: t("adminSubtitle"),
    salesToday: t("salesToday"),
    unpaidInvoices: t("unpaidInvoices"),
    peopleLabel,
    lowStock: t("lowStock"),
    cashflow: t("cashflow"),
    income: t("incomeLabel"),
    expense: t("expenseLabel"),
    net: t("netLabel"),
    aiTitle: t("aiTitle"),
    alertsInbox: t("alertsInbox"),
    staffRanking: t("staffRanking"),
    noScores: t("noScores"),
    recomputeScores: t("recomputeScores"),
    scanInventory: t("scanInventory"),
    briefing: t("briefing"),
    generateBriefing: t("generateBriefing"),
    tasks: t("tasksTitle"),
    createTask: t("createTask"),
    taskTitle: t("taskTitle"),
    adminLinks: t("adminLinks"),
    branches: t("branchesLink"),
    accounting: t("accountingLink"),
    lhdn: t("lhdnLink"),
    adminZone: t("adminZoneLink"),
    marketing: t("marketingIdeas"),
    chatTitle: t("chatTitle"),
    chatPlaceholder: t("chatPlaceholder"),
    chatSend: t("chatSend"),
    activity: t("activityFeed"),
  };
}
