import type { Audience, Niche } from "@/lib/types";

/**
 * The single contract every dashboard surface renders from. Everything here must be
 * plain serializable data so the same object can come from Supabase on the server or
 * from the demo generator in the browser and produce byte-identical layout.
 */

export type DashboardKpis = {
  appointmentsToday: number;
  noShowToday: number;
  salesToday: number;
  txnToday: number;
  unpaidCount: number;
  unpaidTotal: number;
  customerCount: number;
  lowStockCount: number;
  lowStockNames: string[];
  incomeMonth: number;
  expenseMonth: number;
  lhdnPendingCount: number;
  lhdnRejectedCount: number;
  orgHasTin: boolean;
};

export type DashboardInvoiceRow = {
  id: string;
  title: string;
  invoice_number: string;
  status: string;
  total: number;
  created_at: string;
};

export type DashboardAppointmentRow = {
  id: string;
  title: string;
  starts_at: string;
  ends_at: string;
  status?: string;
  notes?: string | null;
  customers?: {
    name: string;
    risk_level?: "high" | "medium" | "low" | null;
    allergies?: string | null;
  } | null;
};

export type DashboardSaleRow = {
  id: string;
  label: string;
  customer: string | null;
  amount: number;
  paid_at: string;
};

export type DashboardTopSellerRow = {
  name: string;
  units: number;
};

export type DashboardOpeningHours = {
  openHour: number;
  closeHour: number;
  closedWeekdays: number[];
};

export type CardTone = "neutral" | "good" | "warn" | "danger";

export type NicheCardStat = {
  /** Message key under DashCards.stat */
  key: string;
  value: string;
  tone?: CardTone;
};

export type NicheCardRow = {
  id: string;
  primary: string;
  secondary?: string | null;
  meta?: string | null;
  tone?: CardTone;
};

/**
 * Niche cards are data only. Every label is looked up by key in the renderer so one
 * component draws all of them and no niche can invent its own layout.
 */
export type NicheCardPayload = {
  /** Matches a card id in the registry. */
  id: string;
  stats: NicheCardStat[];
  rows: NicheCardRow[];
  href?: string;
};

export type RevenueTrendPoint = {
  /** YYYY-MM-DD in Malaysia time, or a bucket key when the window is not daily. */
  day: string;
  amount: number;
  /** Axis label; falls back to the day of month when absent. */
  label?: string;
};

export type ActivityEntry = {
  id: string;
  actor: string | null;
  summary: string;
  created_at: string;
};

export type MarketingIdea = {
  id: string;
  title: string;
  body: string;
};

export type AlertSeverity = "low" | "medium" | "high";
export type AlertStatus = "open" | "investigating" | "resolved";

/** One row of the alerts inbox. Plain serializable so demo and live match. */
export type AlertRow = {
  id: string;
  type: string;
  severity: AlertSeverity;
  title: string;
  message: string;
  status: AlertStatus;
  staffName: string | null;
  created_at: string;
};

export type TaskRow = {
  id: string;
  title: string;
  notes: string | null;
  status: "open" | "done";
  source: "manual" | "alert" | "ai";
  due_date: string | null;
  assigneeName: string | null;
  created_at: string;
};

/** One person's daily rule-based score, from the staff_scores table. */
export type StaffScoreEntry = {
  userId: string;
  name: string;
  score: number;
  sales: number;
  /** refunds + voids that day */
  mistakes: number;
};

/** The cached daily briefing, generated by the LLM or the rule fallback. */
export type BriefingSlice = {
  content: string;
  /** Model name, or "rules" when the deterministic fallback wrote it. */
  model: string;
  for_date: string;
  generated_at: string;
};

/** Assignable teammate for the task picker. */
export type TaskAssignee = {
  userId: string;
  name: string;
};

/** Owner-only slice. Absent for the staff audience so the data never leaves the server. */
export type AdminInsights = {
  revenueTrend: RevenueTrendPoint[];
  lastMonthIncome: number;
  lastMonthExpense: number;
  receivablesCurrent: number;
  receivablesOverdue: number;
  receivablesOverdueCount: number;
  overdueAfterDays: number;
  activity: ActivityEntry[];
  teamSize: number;
  branchCount: number;
  marketing: MarketingIdea[];
  /** Ops Brain: open + investigating alerts, newest first. Empty when disabled. */
  alerts: AlertRow[];
  /** Ops Brain: recent tasks across the org. Empty when disabled. */
  tasks: TaskRow[];
  /** Ops Brain: today's top scorers, best first. Empty when disabled. */
  staffRanking: StaffScoreEntry[];
  /** Ops Brain: cached AI briefing for today. Null until generated. */
  briefing: BriefingSlice | null;
  /** Teammates a task can be assigned to. Empty when disabled. */
  members: TaskAssignee[];
};

export type SharedDashboardData = {
  niche: Niche;
  audience: Audience;
  orgName: string;
  /** Name shown in the greeting — the member's own name in the real app. */
  greetingName: string;
  /** ISO timestamp the whole screen is rendered against, so lists and timetable agree. */
  nowIso: string;
  hours: DashboardOpeningHours;
  kpis: DashboardKpis;
  recentInvoices: DashboardInvoiceRow[];
  upcomingAppointments: DashboardAppointmentRow[];
  todayAppointments: DashboardAppointmentRow[];
  todaySales: DashboardSaleRow[];
  topSellers: DashboardTopSellerRow[];
  nicheCards: NicheCardPayload[];
  adminInsights?: AdminInsights;
  /**
   * Ops Brain flag from the organizations row. False when the column is missing
   * (migration not applied yet) so the new cards simply stay hidden.
   */
  opsBrainEnabled: boolean;
  /** Tasks assigned to the signed-in member (staff audience). */
  myTasks?: TaskRow[];
  /** The signed-in member's own score for today (staff audience). */
  myScore?: StaffScoreEntry | null;
  /** True only for the homepage demo, so action buttons never fire real mutations. */
  demo?: boolean;
};

export const REVENUE_TREND_DAYS = 14;
export const RECEIVABLE_OVERDUE_DAYS = 30;

export function lhdnOutstanding(kpis: DashboardKpis) {
  return kpis.lhdnPendingCount + kpis.lhdnRejectedCount;
}
