import type { StaffDashLabels } from "@/components/dashboards/StaffDashboardView";
import type { AdminDashLabels } from "@/components/dashboards/AdminDashboardView";

type TFn = (key: string) => string;

export function staffDashLabelsFromT(t: TFn, peopleLabel: string): StaffDashLabels {
  return {
    welcome: t("welcome"),
    salesToday: t("salesToday"),
    appointmentsToday: t("appointmentsToday"),
    unpaidInvoices: t("unpaidInvoices"),
    lowStock: t("lowStock"),
    peopleLabel,
    aiTitle: t("aiTitle"),
    dailyClose: t("dailyClose"),
    dailyCloseHint: t("dailyCloseHint"),
    closeIncome: t("closeIncome"),
    closeUnpaid: t("closeUnpaid"),
    closeNoShow: t("closeNoShow"),
    closeTxnToday: t("closeTxnToday"),
    closeLowStock: t("closeLowStock"),
    closeLhdnPending: t("closeLhdnPending"),
    closeLhdnRejected: t("closeLhdnRejected"),
    closeNone: t("closeNone"),
    closeOpenInvoices: t("closeOpenInvoices"),
    closeOpenInventory: t("closeOpenInventory"),
    closeOpenLhdn: t("closeOpenLhdn"),
    closeOpenPos: t("closeOpenPos"),
    quickActions: t("quickActions"),
    recentInvoices: t("recentInvoices"),
    upcomingAppointments: t("upcomingAppointments"),
    todaySales: t("todaySales"),
    todaySalesEmpty: t("todaySalesEmpty"),
    topSellers: t("topSellers"),
    topSellersEmpty: t("topSellersEmpty"),
    miniTimetable: t("miniTimetable"),
    occupied: t("occupied"),
    free: t("free"),
    clinicClosed: t("clinicClosed"),
    publicHoliday: t("publicHoliday"),
    myTasks: t("myTasks"),
    myScore: t("myScore"),
    noTasks: t("noTasks"),
    markDone: t("markDone"),
    invoices: t("invoicesLink"),
    appointments: t("appointmentsLink"),
    pos: t("posLink"),
    inventory: t("inventoryLink"),
    alerts: t("alertsLink"),
    cycleCount: t("cycleCountLink"),
  };
}

export function adminDashLabelsFromT(t: TFn): AdminDashLabels {
  return {
    welcome: t("welcome"),
    subtitle: t("adminSubtitle"),
    monthRevenue: t("monthRevenue"),
    vsLastMonth: t("vsLastMonth"),
    outstanding: t("outstanding"),
    overdue: t("overdue"),
    teamSize: t("teamSize"),
    branches: t("branchesLink"),
    openAlerts: t("openAlerts"),
    revenueTrend: t("revenueTrend"),
    staffRanking: t("staffRanking"),
    noScores: t("noScores"),
    recomputeScores: t("recomputeScores"),
    staffActivity: t("staffActivity"),
    noActivity: t("noActivity"),
    alertsInbox: t("alertsInbox"),
    noAlerts: t("noAlerts"),
    reviewAlerts: t("reviewAlerts"),
    scanInventory: t("scanInventory"),
    cashflowPlanning: t("cashflowPlanning"),
    income: t("incomeLabel"),
    expense: t("expenseLabel"),
    net: t("netLabel"),
    runway: t("runway"),
    openAccounting: t("accountingLink"),
    marketing: t("marketingIdeas"),
    briefing: t("briefing"),
    generateBriefing: t("generateBriefing"),
    delegatedTasks: t("delegatedTasks"),
    noTasks: t("noTasks"),
    manageTasks: t("manageTasks"),
    adminTools: t("adminLinks"),
    adminZone: t("adminZoneLink"),
    addBranch: t("addBranch"),
    lhdn: t("lhdnLink"),
    teamPage: t("teamPage"),
    performancePage: t("performancePage"),
    chatTitle: t("chatTitle"),
    chatPlaceholder: t("chatPlaceholder"),
    chatSend: t("chatSend"),
    demoNotice: t("demoNotice"),
  };
}
