import type { Niche } from "@/lib/types";

/** Sample org names shown inside the homepage dashboard demo. */
export const DEMO_ORG: Record<Niche, string> = {
  clinic: "Klinik Harmoni",
  retail: "ProSupply Mart",
  salon: "Glow Studio",
  pharmacy: "CarePlus Pharmacy",
  optical: "ClearVision Optical",
  tuition: "BrightMind Tuition",
  workshop: "AutoFix Workshop",
  gym: "Palio Fitness",
  vet: "Paws & Care Vet",
  fashion: "Thread & Co",
  electronics: "Gadget Hub",
  wholesale: "BulkTrade Supply",
  laundry: "FreshFold Laundry",
  physio: "MoveWell Physio",
  lab: "PathLab Diagnostics",
  fnb: "Table & Flame",
  hotel: "RestEasy Homestay",
  property: "Homefront Realty",
  courier: "SwiftParcel",
  contractor: "BuildRight Contracts",
  manufacturing: "ForgeWorks MFG",
  legal: "Aman Counsel",
  events: "Momenta Events",
  farm: "GreenAcre Farm",
};

export const LANDING_TITLE_KEY: Record<Niche, string> = {
  clinic: "clinicTitle",
  retail: "retailTitle",
  salon: "salonTitle",
  pharmacy: "pharmacyTitle",
  optical: "opticalTitle",
  tuition: "tuitionTitle",
  workshop: "workshopTitle",
  gym: "gymTitle",
  vet: "vetTitle",
  fashion: "fashionTitle",
  electronics: "electronicsTitle",
  wholesale: "wholesaleTitle",
  laundry: "laundryTitle",
  physio: "physioTitle",
  lab: "labTitle",
  fnb: "fnbTitle",
  hotel: "hotelTitle",
  property: "propertyTitle",
  courier: "courierTitle",
  contractor: "contractorTitle",
  manufacturing: "manufacturingTitle",
  legal: "legalTitle",
  events: "eventsTitle",
  farm: "farmTitle",
};
